# Generated by Django 5.1.1 on 2026-03-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_is_favorited_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Cлаг'),
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
