# Generated by Django 5.1.1 on 2026-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.CharField(max_length=50, verbose_name='Количество'),
        ),
    ]
