# Generated by Django 5.1.1 on 2026-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True, verbose_name='Cлаг'),
        ),
    ]
