# Generated by Django 5.1.1 on 2026-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ('username',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'ordering': ('-blacklist_time',), 'verbose_name': 'токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='blacklist_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время удаления'),
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.CharField(max_length=500, verbose_name='Токен'),
        ),
    ]
